#!/usr/bin/env python3
"""Sync PMP lesson images from the abovetarget-pwa build output into this app.

The PWA keeps full-resolution images in its build output (pulled from R2);
its repo `public/images` are compressed placeholders, so we source from build.

Usage:
    python3 scripts/sync-pwa-images.py copy   [--src <pwa_build_images_dir>]
    python3 scripts/sync-pwa-images.py genmap
    python3 scripts/sync-pwa-images.py verify [--pwa-data <pwa pmp json dir>]
    python3 scripts/sync-pwa-images.py all    [--src ...] [--pwa-data ...]
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LESSONS_IMG_DIR = ROOT / "assets" / "images" / "lessons"
DATA_DIR = ROOT / "assets" / "data"
MAP_TS = ROOT / "src" / "data" / "lesson-images.ts"

DEFAULT_SRC = Path(
    "/Users/hoangnamhai/Documents/workspace/abovetarget-pwa/build/client/images"
)
DEFAULT_PWA_DATA = Path(
    "/Users/hoangnamhai/Documents/workspace/abovetarget-pwa/app/lib/data/pmp"
)

IMG_RE = re.compile(r"/images/[A-Za-z0-9_\-]+\.webp")

HEADER = """import { ImageSourcePropType } from 'react-native';

// Map of all lesson images
// Keys match the paths in lesson JSON files (e.g., "/images/A1L1_comic_menu.webp")
// AUTO-GENERATED by scripts/sync-pwa-images.py genmap — do not edit by hand.
const lessonImages: Record<string, ImageSourcePropType> = {
"""

FOOTER = """};

// Default placeholder image
const defaultImage = require('../../assets/images/lessons/A1L1_comic_menu.webp');

/**
 * Get a lesson thumbnail image by path
 * Used for lesson list cards
 */
export function getLessonThumbnail(thumbnailPath: string): ImageSourcePropType {
  return lessonImages[thumbnailPath] || defaultImage;
}

/**
 * Get any lesson image by path
 * Used for diagrams, comics, and other images in lesson content
 */
export function getLessonImage(imagePath: string): ImageSourcePropType {
  return lessonImages[imagePath] || defaultImage;
}

/**
 * Check if an image exists for the given path
 */
export function hasLessonImage(imagePath: string): boolean {
  return imagePath in lessonImages;
}

export { lessonImages };
"""


def copy_images(src: Path) -> int:
    if not src.is_dir():
        sys.exit(f"ERROR: source dir not found: {src}")
    LESSONS_IMG_DIR.mkdir(parents=True, exist_ok=True)
    n = 0
    for img in sorted(src.glob("*.webp")):
        shutil.copy2(img, LESSONS_IMG_DIR / img.name)
        n += 1
    print(f"Copied {n} images from {src} -> {LESSONS_IMG_DIR}")
    return n


def gen_map() -> int:
    files = sorted(p.name for p in LESSONS_IMG_DIR.glob("*.webp"))
    body = "".join(
        f"  '/images/{name}': require('../../assets/images/lessons/{name}'),\n"
        for name in files
    )
    MAP_TS.write_text(HEADER + body + FOOTER, encoding="utf-8")
    print(f"Wrote {MAP_TS} with {len(files)} image entries")
    return len(files)


def verify(pwa_data: Path) -> None:
    # 1) Coverage: every referenced image must exist as a require-map key.
    map_src = MAP_TS.read_text(encoding="utf-8")
    keys = set(re.findall(r"'(/images/[A-Za-z0-9_\-]+\.webp)'\s*:", map_src))
    refs = set()
    for jf in DATA_DIR.glob("*.json"):
        refs |= set(IMG_RE.findall(jf.read_text(encoding="utf-8")))
    missing = sorted(refs - keys)
    if missing:
        sys.exit(f"COVERAGE FAIL: {len(missing)} referenced images not in map:\n" +
                 "\n".join(missing))
    print(f"Coverage OK: {len(refs)} referenced images all mapped ({len(keys)} keys).")

    # 2) Question parity: lesson JSON (excluding the index) must match the PWA.
    if not pwa_data.is_dir():
        print(f"SKIP parity: PWA data dir not found: {pwa_data}")
        return
    drift = []
    for jf in sorted(DATA_DIR.glob("*.json")):
        if jf.name == "lessons-index.json":
            continue
        other = pwa_data / jf.name
        if not other.exists():
            drift.append(f"{jf.name}: missing in PWA")
        elif jf.read_bytes() != other.read_bytes():
            drift.append(f"{jf.name}: differs from PWA")
    if drift:
        sys.exit("PARITY FAIL:\n" + "\n".join(drift))
    print("Parity OK: all lesson question JSON match the PWA.")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["copy", "genmap", "verify", "all"])
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC)
    ap.add_argument("--pwa-data", type=Path, default=DEFAULT_PWA_DATA)
    args = ap.parse_args()

    if args.cmd in ("copy", "all"):
        copy_images(args.src)
    if args.cmd in ("genmap", "all"):
        gen_map()
    if args.cmd in ("verify", "all"):
        verify(args.pwa_data)


if __name__ == "__main__":
    main()
